
import Nav2 from './Nav2';
import FilterCourse from './FilterCourse';

import { useDispatch } from 'react-redux';

function Courses(){
    const videos=[
        {
          courseno:1,
          image:"./assest/dsa-1.jpg",
          videolink:"https://www.youtube.com/embed/FuHfoe7U4Fg",
          language:"Hinglish",
          heading:"Dsa Placement Series",
          educatorP1:"Love Babbar ",
          educatorP2:"and 3 more",
          date:"140 lecture",
          detailsP1:"Complete Placement Prepration",
          // detailsP2:"& More",
          working:"college student & working professional",
          price:"Rs. 20000.00",
          offprcie:"40000.00",
          discount:"50% Discount",
          buttoncontent1:"Explore",
          buttoncontent2:"Enroll Now",
          videolink1:"https://www.youtube.com/embed/igGtZWTm0O4",
          src:"https://www.youtube.com/watch?v=WQoB2z67hvY&list=PLDzeHZWIZsTryvtXdMr6rPh4IDexB5NIA",
          category:'dsa',
        },
        {
          courseno:2,
          image:"./assest/webdev-1.jpg",
          videolink1:"https://www.youtube.com/embed/lI7IIOWM0Mo",
          language:"english",
          heading:"Web development",
          educatorP1:"chai aur code ",
          educatorP2:"and 3 more",
          date:"Library -REACT ",
          detailsP1:"carrer guidance | job assurance",
          detailsP2:"& More",
          working:"college student & working professional",
          price:"Rs. 20000.00",
          offprcie:"40000.00",
          discount:"50 %",
          buttoncontent1:"Explore",
          buttoncontent2:"Enroll Now",
          videolink:"https://www.youtube.com/embed/igGtZWTm0O4",
          src:"https://www.youtube.com/results?search_query=chai+aur+code",
          category:'webdev',
        },
        {
          courseno:3,
          image:"./assest/java-1.jpg",
          videolink1:"https://www.youtube.com/embed/ZRS485LxX0s",
          language:"english",
          heading:"Java placement course",
          educatorP1:"Apna college ",
          educatorP2:"and 3 more",
          date:"39 Lecture",
          detailsP1:"carrer guidance | job assurance",
          detailsP2:"& More",
          working:"college student & working professional",
          price:"Rs. 20000.00",
          offprcie:"40000.00",
          discount:"50 %",
          buttoncontent1:"Explore",
          buttoncontent2:"Enroll Now",
          videolink:"https://www.youtube.com/embed/igGtZWTm0O4",
          src:"https://www.youtube.com/watch?v=yRpLlJmRo2w&list=PLfqMhTWNBTe3LtFWcvwpqTkUSlB32kJop",
          category:'java',
        },
        {
          courseno:4,
          image:"./assest/dbms-1.jpg",
          videolink1:"https://www.youtube.com/embed/ZRS485LxX0s",
          language:"english",
          heading:"Dbms placement series",
          educatorP1:"love babar ",
          educatorP2:"and 3 more",
          date:"22 videos",
          detailsP1:"carrer guidance | job assurance",
          detailsP2:"& More",
          working:"college student & working professional",
          price:"Rs. 20000.00",
          offprcie:"40000.00",
          discount:"50 %",
          buttoncontent1:"Explore",
          buttoncontent2:"Enroll Now",
          videolink:"https://www.youtube.com/embed/igGtZWTm0O4",
          category:'dbms'
        },
        {
          courseno:5,
          image:"./assest/app-2.webp",
          videolink1:"https://www.youtube.com/embed/ZRS485LxX0s",
          language:"english",
          heading:"App Development",
          educatorP1:"Priya Bhatiya ",
          educatorP2:"and 3 more",
          date:"Starts on 7 oct 2023",
          detailsP1:"carrer guidance | job assurance",
          detailsP2:"& More",
          working:"college student & working professional",
          price:"Rs. 20000.00",
          offprcie:"40000.00",
          discount:"50 %",
          buttoncontent1:"Explore",
          buttoncontent2:"Enroll Now",
          videolink:"https://www.youtube.com/embed/igGtZWTm0O4",
          category:'appdev'
        },
        {
          courseno:6,
          image:"./assest/cybersecurity-1.webp",
          videolink1:"https://www.youtube.com/embed/ZRS485LxX0s",
          language:"english",
          heading:"Cyber Security",
          educatorP1:"Priya Bhatiya ",
          educatorP2:"and 3 more",
          date:"Starts on 7 oct 2023",
          detailsP1:"carrer guidance | job assurance",
          detailsP2:"& More",
          working:"college student & working professional",
          price:"Rs. 20000.00",
          offprcie:"40000.00",
          discount:"50 %",
          buttoncontent1:"Explore",
          buttoncontent2:"Enroll Now",
          videolink:"https://www.youtube.com/embed/igGtZWTm0O4",
          category:'cs'

        },
        {
            courseno:1,
            image:"./assest/networking-`1.png",
            videolink:"https://www.youtube.com/embed/FuHfoe7U4Fg",
            language:"Hinglish",
            heading:"Computer network",
            educatorP1:"Love Babbar ",
            educatorP2:"and 3 more",
            date:"140 lecture",
            detailsP1:"Complete Placement Prepration",
            // detailsP2:"& More",
            working:"college student & working professional",
            price:"Rs. 20000.00",
            offprcie:"40000.00",
            discount:"50% Discount",
            buttoncontent1:"Explore",
            buttoncontent2:"Enroll Now",
            videolink1:"https://www.youtube.com/embed/igGtZWTm0O4",
            src:"https://www.youtube.com/watch?v=WQoB2z67hvY&list=PLDzeHZWIZsTryvtXdMr6rPh4IDexB5NIA",
            category:'cn'
          },
          {
            courseno:2,
            image:"./assest/ml-4.webp",
            videolink1:"https://www.youtube.com/embed/lI7IIOWM0Mo",
            language:"english",
            heading:"Machine Learning",
            educatorP1:"chai aur code ",
            educatorP2:"and 3 more",
            date:"Library -REACT ",
            detailsP1:"carrer guidance | job assurance",
            detailsP2:"& More",
            working:"college student & working professional",
            price:"Rs. 20000.00",
            offprcie:"40000.00",
            discount:"50 %",
            buttoncontent1:"Explore",
            buttoncontent2:"Enroll Now",
            videolink:"https://www.youtube.com/embed/igGtZWTm0O4",
            src:"https://www.youtube.com/results?search_query=chai+aur+code",
            category:'ml'
          },
          {
            courseno:3,
            image:"./assest/ai-1.jpeg",
            videolink1:"https://www.youtube.com/embed/ZRS485LxX0s",
            language:"english",
            heading:"Artificial intelligance",
            educatorP1:"Apna college ",
            educatorP2:"and 3 more",
            date:"39 Lecture",
            detailsP1:"carrer guidance | job assurance",
            detailsP2:"& More",
            working:"college student & working professional",
            price:"Rs. 20000.00",
            offprcie:"40000.00",
            discount:"50 %",
            buttoncontent1:"Explore",
            buttoncontent2:"Enroll Now",
            videolink:"https://www.youtube.com/embed/igGtZWTm0O4",
            src:"https://www.youtube.com/watch?v=yRpLlJmRo2w&list=PLfqMhTWNBTe3LtFWcvwpqTkUSlB32kJop",
            category:['ai','programminglanguage']
          },
          {
            courseno:7,
            image:"./assest/os-2.jpeg",
            videolink:"https://www.youtube.com/embed/FuHfoe7U4Fg",
            language:"Hinglish",
            heading:"Operating system",
            educatorP1:"apna college ",
            educatorP2:"and 3 more",
            date:"140 lecture",
            detailsP1:"Complete Placement Prepration",
            // detailsP2:"& More",
            working:"college student & working professional",
            price:"Rs. 20000.00",
            offprcie:"40000.00",
            discount:"50% Discount",
            buttoncontent1:"Explore",
            buttoncontent2:"Enroll Now",
            videolink1:"https://www.youtube.com/embed/igGtZWTm0O4",
            src:"https://www.youtube.com/watch?v=WQoB2z67hvY&list=PLDzeHZWIZsTryvtXdMr6rPh4IDexB5NIA",
            category:'os'
          },
          {
            courseno:8,
            image:"./assest/python-1.jpeg",
            videolink1:"https://www.youtube.com/embed/lI7IIOWM0Mo",
            language:"english",
            heading:"Python Course",
            educatorP1:"jeeny ",
            educatorP2:"and 3 more",
            date:"libray",
            detailsP1:"carrer guidance | job assurance",
            detailsP2:"& More",
            working:"college student & working professional",
            price:"Rs. 20000.00",
            offprcie:"40000.00",
            discount:"50 %",
            buttoncontent1:"Explore",
            buttoncontent2:"Enroll Now",
            videolink:"https://www.youtube.com/embed/igGtZWTm0O4",
            src:"https://www.youtube.com/results?search_query=chai+aur+code",
            category:'python'
          },
          {
            courseno:9,
            image:"./assest/cpp-2.png",
            videolink1:"https://www.youtube.com/embed/ZRS485LxX0s",
            language:"english",
            heading:"C++ course",
            educatorP1:"Apna college ",
            educatorP2:"and 3 more",
            date:"39 Lecture",
            detailsP1:"carrer guidance | job assurance",
            detailsP2:"& More",
            working:"college student & working professional",
            price:"Rs. 20000.00",
            offprcie:"40000.00",
            discount:"50 %",
            buttoncontent1:"Explore",
            buttoncontent2:"Enroll Now",
            videolink:"https://www.youtube.com/embed/igGtZWTm0O4",
            src:"https://www.youtube.com/watch?v=yRpLlJmRo2w&list=PLfqMhTWNBTe3LtFWcvwpqTkUSlB32kJop",
            category:['C++','programminglanguage']
          },
     ];
    /*const initialValues={
        title:"",
        category:"",
        price:"",
        productImages : [
            {
              name:"",
              path:"",
            }
        ],
    }*/
    const dispatch=useDispatch();
    // const {courses}=()=>{
    //     const{ username, password } = courses
    // }
    /*onsubmit:async(values,action)=>{
        const{title,category,price,name,path}=values;
    }*/
    
    return(
        <div>
          <Nav2></Nav2>  
          <FilterCourse products={videos}></FilterCourse>
        </div>
    )
}
export default Courses;